# Generated by Django 6.0 on 2026-01-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('upi_qr_code', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('bank_details', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Offer', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.paymentmethod'),
        ),
    ]
