# Generated by Django 6.0 on 2026-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_paymentmethod_rename_end_time_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='executive_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='executive_whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('sales_executive', 'Sales Executive')], max_length=50, unique=True),
        ),
    ]
