# Generated by Django 6.0 on 2026-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_paymentmethod_executive_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='whatsapp_group_link',
            field=models.URLField(blank=True),
        ),
    ]
